#!/usr/bin/env python3
"""List all databases in MongoDB."""
from pymongo import MongoClient


def list_databases():
    client = MongoClient()  # Connects to localhost:27017 by default
    databases = client.list_database_names()
    print("Databases:")
    for db in databases:
        print(f"- {db}")


if __name__ == "__main__":
    list_databases()
